name: md-protein-stability
channels:
  - conda-forge
  - salilab
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - mdtraj
  - dssp
  - nglview
  - jupyterlab
  - ipykernel
  - tqdm
  - pip
  - pip:
      - seaborn
      - pandas
